### ISSUE TITLE
Syntax Highlight on source view

### ISSUE THREAD

**Issue by junghuk** [inf295uci-2015/SeeSoftOnD3#11]
Syntax Highlight on source view.
This, http://alexgorbatchev.com/SyntaxHighlighter/, would be useful.

**Comment by Clairebi** [comment]
I will do this in the next days.

**Comment by Clairebi** [comment]
Hi, I tried to use the syntaxHighlighter to change the display of source code, but one problem I met is how to use this tool in an dynamically generated website. The demo from its official website is all about changing format of static codes. Do you have any ideas? Thanks!

**Comment by VijayKrishna** [comment]
@Clairebi can you give an example of how you would change the format of static codes?

**Comment by junghuk** [comment]
res.content holds the source code. You need to call getHTML() function to highlight code. 
something like this:

line# 413
...
 .text(getHTML(res.content));
...
good luck!

**Comment by Clairebi** [comment]
For example,  a demo code :
<pre class="brush: js">
    /**
     * SyntaxHighlighter
     */
    function foo()
    {
        if (counter <= 10)
            return;
        // it works!
    }
</pre>

The code between <pre...> and </pre> will be highlighted.  
However in our situation, we get the content elsewhere and save it as a variable,  if we put the <pre> </pre> around the variable, the tags will be regarded as string, the outcome is like
"<pre> source code...  </pre>" rather than the source code being highlighted.

**Comment by junghuk** [comment]
@Clairebi Checkout my branch! https://github.com/inf295uci-2015/SeeSoftOnD3/tree/junghuk
It might help you!

**Comment by Clairebi** [comment]
Thanks Junghun!!!

发自我的 iPad

在 2015年5月29日，下午11:43，junghuk <notifications@github.com> 写道：

@Clairebi <https://github.com/Clairebi> Checkout my branch!
https://github.com/inf295uci-2015/SeeSoftOnD3/tree/junghuk
It might help you!

—
Reply to this email directly or view it on GitHub
<https://github.com/inf295uci-2015/SeeSoftOnD3/issues/11#issuecomment-106997188>
.

**Comment by nish2292** [comment]
@Clairebi : There is a problem with the source code display. I can't see it.

![image](https://cloud.githubusercontent.com/assets/9584666/7969395/6501e564-09eb-11e5-9ee1-0fc29526eb05.png)

**Comment by VijayKrishna** [comment]
there seems to be an issue with the indentation.

**Comment by Clairebi** [comment]
Hi Vijay,  what do you mean by indentation issue? It seems to work well
from my view. [image: 内嵌图片 1]

2015-06-03 12:40 GMT-07:00 Vijay Krishna Palepu <notifications@github.com>:

**Comment by VijayKrishna** [comment]
@Clairebi can you give us a screenshot of how it looks on your computer?

**Comment by junghuk** [comment]
![2015-06-03 9 57 27](https://cloud.githubusercontent.com/assets/11988461/7977112/9b7e79b8-0a3b-11e5-8190-88fff987ea54.png)

@Clairebi I changed align of source view. Check master branch.

**Comment by VijayKrishna** [comment]
@nish2292: can you confirm this fix? or any other issues with these changes made my @Clairebi? if all is well, please let @Clairebi know. @Clairebi, once @nish2292 gives you the green light on your changes, please go ahead and close this issue.

**Comment by nish2292** [comment]
Fixed! But the code doesn't overflow. Close this now and work on something else.
