### ISSUE TITLE
Enhanced D3 Autocomplete (?)

### ISSUE THREAD

**Issue by VijayKrishna** [inf295uci-2015/SeeSoftOnD3#12]
How about using this D3 auto-complete plug-in: 
- http://www.brightpointinc.com/clients/brightpointinc.com/library/autocomplete/index.html
- http://www.brightpointinc.com/clients/brightpointinc.com/library/autocomplete/download.html

It has some advantages over the current implementation:
1. It allows us to do auto complete on sub-strings, not just string-starts, i.e. typing `S` can give us both `SourceViewer` and `ViewSurface`.
2. It narrows our dependency list to just d3 (and this small plugin on top of that), and gets rid of jQuery -- if we are using jQuery for the only purpose of auto-complete.

Thoughts?

**Comment by nish2292** [comment]
I'll work on this now.

**Comment by VijayKrishna** [comment]
If this is done, let's close it!

**Comment by nish2292** [comment]
Yeah it's done.
