### ISSUE TITLE
SeeSoft Zoom

### ISSUE THREAD

**Issue by nish2292** [inf295uci-2015/SeeSoftOnD3#17]
On zooming in on a SeeSoft view of a particular program, @vijaykrishna suggested that a new tab with a zoomed in version of the file chosen should be made. The tabs get cascaded next to each other and become easier to view.

**Comment by nish2292** [comment]
![screenshot 2015-06-03 16 32 13](https://cloud.githubusercontent.com/assets/9584666/7973777/364944b0-0a0e-11e5-8f98-c01f1d8444fe.png)
Tabs are working for single files. Can anyone give me suggestions as to what else I can do.

**Comment by VijayKrishna** [comment]
Put small crosses on the tabs, in case we have to close some of them...

**Comment by nish2292** [comment]
I'm not sure how milestones work exactly. I'll add the cross buttons.

**Comment by nish2292** [comment]
And it works.
1be0f184a8af215aa6d97b075c32b1775fce0422

![screenshot 2015-06-03 16 56 09](https://cloud.githubusercontent.com/assets/9584666/7974013/98a12792-0a11-11e5-817e-d6e58b945d9e.png)

**Comment by nish2292** [comment]
![screenshot 2015-06-03 18 11 46](https://cloud.githubusercontent.com/assets/9584666/7974886/5770416c-0a1c-11e5-9cfe-7665d8f7f9f6.png)
Better UI 2500aecaed01fd445001dbfe3bfcf03cdee7ff91

**Comment by junghuk** [comment]
I like Tab.
But when I go back to tree tab, it zoom out to root, so I can't see the details view.

**Comment by nish2292** [comment]
I don't know why that's happening. Before I changed it, the first click anywhere else after the show details view would normally zoom back to the root as well. Can you fix it?

**Comment by junghuk** [comment]
@nish2292 let me try :-)

**Comment by nish2292** [comment]
This happens only on the double click though. I you follow it with the single clicks, you can still see it.
Also the coloring looks much better now.

**Comment by junghuk** [comment]
@nish2292 I add the following code in line#122. Then it works better in my computer.

if(d3.event !=null) d3.event.stopPropagation();

**Comment by nish2292** [comment]
It works! Well done man. I now know how and when to use that function.

**Comment by nish2292** [comment]
I think this general issue is taken care of. I'll create another specific issue which is a next level problem.
