### ISSUE TITLE
Brightness for Suspiciousness with Cushion Treemaps

### ISSUE THREAD

**Issue by VijayKrishna** [inf295uci-2015/SeeSoftOnD3#18]
So, i was thinking why this was not possible with d3.js :)
- [x] Implement the brightness idea proposed by @junghuk with a radial gradient in the tree map, essentially getting something similar to a cushion treemap.
- [x] Make a central bright spot in each cell in the tree map
- [x] Implement the bright spot using svg's radial gradient, if we are using svg for the tree-map cells.
- [x] Tie the radius of the bright spot using some metric like suspiciousness.

further-reading/code-examples that can help with this feature request:
- https://gist.github.com/dholth/1368205
- https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients#Radial_Gradient
- http://bl.ocks.org/pbogden/14864573a3971b640a55
- http://www.win.tue.nl/~vanwijk/ctm.pdf

**Comment by junghuk** [comment]
I guess that cushion view makes each tile more distinguishable because the edge of tile is dark, which makes boundary line.

**Comment by junghuk** [comment]
I also think about using patterns on tile, such as this. https://github.com/iros/patternfills
I'm not sure which information it may represent.

**Comment by VijayKrishna** [comment]
> I guess that cushion view makes each tile more distinguishable because the edge of tile is dark, which makes boundary line.

Yes @junghuk, that was the other intention behind this feature request.

**Comment by nish2292** [comment]
I honestly think that it may just be too much information. But we should definitely try it out nonetheless.

**Comment by VijayKrishna** [comment]
If you want to take a crack at this feature, feel free. I know that i have assigned it to myself, but that is because of its dependency on tarantula-data. I can still be the owner of the feature (so if anything goes wrong, it will be on me).

**Comment by nish2292** [comment]
I got this. I was thinking of adding a tool-tip to every rectangle of the tree map anyway.

**Comment by VijayKrishna** [comment]
@nish2292: its the 29th! :D Time to get started i suppose (I am kidding of course)

**Comment by nish2292** [comment]
Vijay you taskmaster!

**Comment by nish2292** [comment]
Guys I tried the radialGradient on d3 here : http://jsfiddle.net/pz9k5bfz/
It seems to work here but has no effect on the code for some reason.

**Comment by nish2292** [comment]
And  3/4 done implemented. I didn't yet tie the any metric to the bright spot parameters yet.

**Comment by nish2292** [comment]
Tied the radius to commit information in 90e7eba9d8a640956d8bb37255148892a056cf1c.

**Comment by nish2292** [comment]
Guys I need someone to think of how to represent extra data using the gradient in the tree map. I need a different perspective. Please share some ideas that you have.
