### ISSUE TITLE
Add number of commits info

### ISSUE THREAD

**Issue by junghuk** [inf295uci-2015/SeeSoftOnD3#2]
Grep Number of commits from Github API and put color or number to each title.

I am not sure which color scheme is the best until I can see actual result.
So color scheme should be implemented easy to change & compare.

Features:
- [ ] Red Color: recent commits, Grey: no change. 
- [ ] Options: compare recent commits only or all commits.
- [ ] Show number of commits when the tile is zoomed.

**Comment by junghuk** [comment]
I made a tile brighter based on commit info.
I need to normalize the brightness to get even result.

**Comment by AnshumanSanghvi** [comment]
I am going to work on listing number of commits from Github API, and putting color/number in title.

I looked up the API and found the statistics part where this is possible. https://developer.github.com/v3/repos/statistics/
commit counts can either be displayed as per user weekly counts or yearly counts.

**Comment by nish2292** [comment]
It's a similar issue as #3 
Number of commits displayed as the gradient.
