### ISSUE TITLE
Github API rate limit

### ISSUE THREAD

**Issue by junghuk** [inf295uci-2015/SeeSoftOnD3#5]
We can call Github API only 60 times in 24 hours.
We may solve this problem by adding Oauth to every request.

I made offline option in js file to avoid this restriction,
but we need to solve this problem anyway.

ref: https://developer.github.com/v3/rate_limit/

**Comment by VijayKrishna** [comment]
"For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour" --- https://developer.github.com/v3/#rate-limiting ... so its really 60*24 requests every day :) but i agree with your overall comment, that we need to set up Oauth... That will buy us tremendous rate limits!

**Comment by junghuk** [comment]
I add client_id and client_secret values to ZoomableTreeMap.html.
If it has any bug, please let me know
