### ISSUE TITLE
Seesoft View 

### ISSUE THREAD

**Issue by junghuk** [inf295uci-2015/SeeSoftOnD3#6]
Features:
- [ ] When a tile is zoomed, show seesoft view.  
- [ ] actual source code can be displayed when mouse is on the seesoft view.

**Comment by VijayKrishna** [comment]
So, i like we discuessed in class today: how about see if we can have a separate section or at least a different tab, for the seesoft view?

**Comment by VijayKrishna** [comment]
@nish2292 how much of this would you say is done? ... if all of it, then let's close it!

**Comment by nish2292** [comment]
Most of it is done I'd say. It's just about moving it around and manipulating the the divs that it is contained within.
